In [88]:
#Задание 1
#Создайте numpy array с элементами от числа N до 0
#например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).



N=int(input('Введите число: '))
p=list(np.arange(0,N-0))
y=[]
[y.append(x) for x in reversed(p)]
   
print(np.array([y]))
print(type(np.array([y])))

Введите число: 7
[[6 5 4 3 2 1 0]]
<class 'numpy.ndarray'>


In [86]:
type(np.array([0,7]))

numpy.ndarray

In [98]:
#Задание 2
#Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.
N=int(input('Введите число: '))
p=list(np.arange(0,N-0))
y=[]
[y.append(x) for x in reversed(p)]
v=np.diag(np.array(y),k=0) 
print(v)
print(np.sum(v))


Введите число: 5
[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]
10


In [107]:
#Задание 3
#Решите систему уравнений:
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3
from numpy import linalg

a=[[4,2,1],
   [1,3,0],
   [0,5,4]]
b=[4,12,-3]

print(linalg.solve(a,b))
print(np.allclose(np.dot(a,linalg.solve(a,b)),b))

[ 0.46666667  3.84444444 -5.55555556]
True


In [151]:
#Задание 4
import matplotlib.pyplot as plt
from numpy import linalg
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
y=[]
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
for x in users_stats:
    a=np.linalg.norm(x)
    b=np.linalg.norm(next_user_stats)
    y.append(np.dot(x,next_user_stats)/a*b)
print(max(y))

4.743416490252569
